### ISSUE TITLE
Similar project on Windows??

### ISSUE THREAD

**Issue by jhouxatjvx** [themanyone/whisper_dictation#4]
Do you know of any similar project on Windows?

Or would you be able to explain what parts of this project I could utilize to build my own frontend on windows?

I know you've put a lot of thought already into how to do real-time streaming transcription with whisper.  There is the issue of figuring out how to provide chunks to whisper.cpp so that it can work on them, and would definitely like to know what solution you landed on.

I am a C# dev lacking knowledge on whisper and even on using GGML/GGUF ai models.  Trying to learn. :)

**Comment by NotBrianZach** [comment]
it's been a while since I looked at project but I was checking back in for a sec, and in the source code it looks like there is hotkeys for windows, I was thinking to myself, why wouldn't it run on windows? couldn't think of a reason just glancing at source, though I'm primarily linux myself I would think all you need to do is get the relevant python or possibly c++ dependencies onto your windows box

**Comment by jhouxatjvx** [comment]
You are correct! I am such a newb!

I tried to execute the client from WSL Ubuntu, which threw a display error. Totally wasn't thinking. I need to execute it in windows directly durrrr!

**Comment by NotBrianZach** [comment]
don't forget close issue 😂

**Comment by jhouxatjvx** [comment]
thank you :)
