### ISSUE TITLE
Continuous as a service?

### ISSUE THREAD

**Issue by CaydenPierce** [themanyone/whisper_dictation#5]
I want to have this run continuously all the time. 

I'd like to make a hotkey combo that turns this on, and then just start speaking to type, and press the same hotkey combo to turn it off. Ideally, in Ubuntu, it would show some indication in the top right that it's active when active.

This looks like a great project, but it only runs for 10 minutes at a time? Could we set this up as a system service (`systemctl`) to start on boot and just always be available? I have a decent laptop, idc about it using battery and/or VRAM.

Thoughts on this? Can lend a hand with implementation if needed, I super want a Linux STT that works everywhere all the time. 

Also - are there other open source/free solutions that are already do this perhaps?

Thanks.

**Comment by CaydenPierce** [comment]
I should also say - I don't need voice commands or images, etc., so perhaps this makes more sense: https://github.com/themanyone/voice_typing

However, I want the very high speed/low latency, so that's why I commented on this repo.

**Comment by themanyone** [comment]
I didn't think about that, since it's not secure having a service that can type on the keyboard potentially unsupervised. I like to be there looking at it. It's just something I launch with a hotkey when needed. I don't like to keep anything running also because it uses memory I need to run a large language model now and then.

But I could make it dump the recording and start over. Then it could theoretically run forever as a userspace service, not system-wide. Then I could just copy the text where mimic3 describes how to set up their user service. Good idea.

As far as hotkeys, those are different on every desktop/session/window manager combination. And there are independent services for hotkeys that work outside of X11/Wayland graphics entirely. Best leave that up to the user.

**Comment by CaydenPierce** [comment]
Is this a feature you plan to add in near future?

**Comment by themanyone** [comment]
It should be able to run continuously now. Just beware of situations where it could listen or pick up noise from the environment and type random commands into open terminal windows or such. Security will come knocking.
