### ISSUE TITLE
Audio is not being recorded if silence isn't detected before a recording, meaning beginnings get lopped off

### ISSUE THREAD

**Issue by C0rn3j** [themanyone/whisper_dictation#8]
```python
				if rms < dB: # wait for startup clicks and pops to die down
					self.silence = 1 # got it, we have silence!
				elif rms > dB and self.silence: # now wait for voice
```

I have ended up replacing this code with this

```python
				if rms > dB: # now wait for voice
```

To fix the issue.

To reproduce, one has to start speaking immediately after processing were done, or immediately after launching the whisper client.

I have ended up losing long audios because there's no pause, and lots of continuous speech.  
Lead time setting won't fix this, as the length of the spoken text without pause will be dynamic.

**Comment by themanyone** [comment]
It depends on audio hardware and keys or switches used to turn the mic on and off. When I first started this project, my setup was quite noisy.

It was a requirement to wait for silence first because if the volume happened to be too high when it started, it would just sit there and record continuously, filling up the disk. And when it finally did get around to processing the audio, it would take a long time. It's sort of a safety feature if it can detect silence at the beginning, then it can also detect silence between clips.
 
Totally unnecessary if you're turning it on and off with a key. If you have lots of continuous speech, you can also reduce the threshold time. That way it can recognize individual sentences, instead of one large paragraph that might get delayed, typed into the wrong window, etc.

**Comment by C0rn3j** [comment]
I have an always-on microphone setup.  

> And when it finally did get around to processing the audio, it would take a long time. 

I also have an overkill 4090 setup, so the processing is extremely quick.

`/tmp` is tmpfs by default, so it's not writing anything to disk, at worst it's taking a few megabytes of RAM.

I think it'd make sense to define optional max audio length to prevent an eternally-going-on-clip, and make the silence detection also optional, as it makes no sense for my setup at least, but I see that someone else with a different setup might find it useful.

**Comment by themanyone** [comment]
It has a max audio length of 10 minutes. But I totally rewrote `record.py` from scratch to expose that as an option. Also, it does not use `ffmpeg` anymore. I was kind of embarrassed about that dependency. Instead, I have it preroll a delayed recording with a valve. Much more intuitive. Exposed GStreamer's powerful plugin facility. Doc update.

**Comment by themanyone** [comment]
The update seems mostly stable now.

**Comment by themanyone** [comment]
The update seems mostly stable now.
